### ISSUE TITLE
Crash on rapid switch

### ISSUE THREAD

**Issue by williamieong** [TeamCaffeine/HotSwap#43]
Currently on master, if you search quickly between the search bar and any other fragment, it will crash.

The two errors we get are either:
- java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.support.v4.app.FragmentActivity.getApplicationContext()' on a null object reference
- java.lang.IllegalStateException: GoogleApiClient is not connected yet.

**Comment by jschadaway** [comment]
Resolved by #51
