### ISSUE TITLE
Setting addresses from ListItemActivity causes crash when returning to the profile address fragment

### ISSUE THREAD

**Issue by alexrosenfeld10** [TeamCaffeine/HotSwap#91]
Steps:

1. add address to profile VIA list item activity
2. return to profile
3. add another address

**Comment by alexrosenfeld10** [comment]
Note -- after testing on an old APK of this app that does not have the set item picture code, this bug does not occur.

**Comment by jschadaway** [comment]
monkaS

**Comment by alexrosenfeld10** [comment]
@jschadaway sorry mang :biblethump:

**Comment by alexrosenfeld10** [comment]
Also keyboard UI now slides up we should change that back in the manifest (soft input mode)

**Comment by alexrosenfeld10** [comment]
@jschadaway fixed both. Simple call to super.onActivityResult() fixed it.
